### PR TITLE
Some more changes to code

### PR DESCRIPTION
**Pull request by bharatr21**

### CODE REVIEW

**Comment by Genius1237** [comment]
Wouldn't it be better to just remove the version number entirely?

**Comment by bharatr21** [comment]
Not really, since it is not guaranteed to work with _lower_ versions of the dependencies. For example, `AlexNet` could have been added in torchvision  later than 1.0 etc.

Edit: Also for Python's sake, please use an editor with PEP8 linting, it helps :+1:

**Comment by Genius1237** [comment]
In the current state, will it install the latest version of the packages or the version you specified?

**Comment by bharatr21** [comment]
> In the current state, will it install the latest version of the packages or the version you specified?

`>=` installs latest, `==` pins them in case later versions introduce bugs, but we needn't worry about that for now.

Here `pip install -r requirements.txt` is expected to work perfectly for anyone who just clones the repo and wants to run it, to further simplify it, it needs to be uploaded to PyPI and all

**Comment by Genius1237** [comment]
Can you add a license file also? MIT license should do

**Pull request merged**
